# Generated by Django 4.0.4 on 2022-05-01 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=2048)),
                ('tag', models.CharField(choices=[('BUG', 'Bug'), ('ENHANCEMENT', 'Amélioration'), ('TASK', 'Tâche')], max_length=12)),
                ('priority', models.CharField(choices=[('HIGH', 'Élevée'), ('NORMAL', 'Normal'), ('LOW', 'Faible')], max_length=12)),
                ('status', models.CharField(choices=[('TO_DO', 'À faire'), ('IN_PROGRES', 'En cours'), ('DONE', 'Terminé')], max_length=12)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
