# Generated by Django 4.0.4 on 2022-05-13 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0006_alter_issue_assignee_user_alter_issue_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='issue_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
