# Generated by Django 4.0.4 on 2022-05-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_alter_issue_project'),
        ('comments', '0004_alter_comment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='issues.issue'),
        ),
    ]
